services:
  - type: web
    name: padhai-dost-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r python-backend/requirements.txt
    startCommand: uvicorn python-backend.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEMO_MODE
        value: "true"
